---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-calculator-sample-domain-v1-sum
  failurePolicy: Fail
  name: vsum.kb.io
  rules:
  - apiGroups:
    - calculator.sample.domain
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - sums
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-calculator-sample-domain-v1-sum
  failurePolicy: Fail
  name: vsum.kb.io
  rules:
  - apiGroups:
    - calculator.sample.domain
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - sums
  sideEffects: None
