# permissions for end users to view sums.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sum-viewer-role
rules:
- apiGroups:
  - calculator.sample.domain
  resources:
  - sums
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - calculator.sample.domain
  resources:
  - sums/status
  verbs:
  - get
